### PR TITLE
Fix for issue #201

### LINKED ISSUE #201: FAB Icon hides when it shouldn't in GameDetails screen
When switching between two tabs in the GameDetails screen the fab will hide on the live or post game thread fragments when it should be displayed.

### PR DESCRIPTION
**Pull request by cmspray**
When the visibility of the GameThread is set to true and the presenter has been created, we now show the FAB if there is a current submission.

Closes #201

### CODE REVIEW

File: app/src/main/java/com/gmail/jorgegilcavazos/ballislife/features/gamethread/GameThreadPresenterV2.kt [hunk 1]
```diff
@@ -145,13 +145,19 @@ class GameThreadPresenterV2 @Inject constructor(
     super.detachView()
   }
 
-  fun loadGameThread() {
-    val gameThreadsObs = if (shouldStream) {
-      gameThreadsRepository.gameThreads(home, visitor, gameTimeUtc, type)
-          .repeatWhen({ o -> o.delay(10, TimeUnit.SECONDS) })
-    } else {
-      gameThreadsRepository.gameThreads(home, visitor, gameTimeUtc, type)
+	fun onVisible() {
```
Comment (jorgegil96) [inline app/src/main/java/com/gmail/jorgegilcavazos/ballislife/features/gamethread/GameThreadPresenterV2.kt]: Looks like the indentation got messed up. Please fix.
